server:
  port: ${port:2222}
  error:
    include-stacktrace: never

spring:
  application:
    name: person-service

info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      version: @java.version@

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    level:
      org.springframework.data.mongodb.core.MongoTemplate: DEBUG
  file: app.log

management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true
    mongo:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: production
  application:
    name: person-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: microservices
      username: micro
      password: micro
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration